//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appva.Azure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appva.Azure.DebugFormats", typeof(DebugFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exception while sending push to: {0} with payload: {1}&quot;.
        /// </summary>
        internal static string PushException {
            get {
                return ResourceManager.GetString("PushException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a push notification executing.
        /// </summary>
        internal static string PushExecute {
            get {
                return ResourceManager.GetString("PushExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Push responded with success: {0}, failure: {1}, state: {2} for devices: {3}&quot;.
        /// </summary>
        internal static string PushOutcomeResponse {
            get {
                return ResourceManager.GetString("PushOutcomeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while registrering device with device token: {0}.
        /// </summary>
        internal static string RegistrationException {
            get {
                return ResourceManager.GetString("RegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register device for push notifications executing.
        /// </summary>
        internal static string RegistrationExecute {
            get {
                return ResourceManager.GetString("RegistrationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Registration for device id: {0} responded with registration id: {1}, tags: {2}&quot;.
        /// </summary>
        internal static string RegistrationResponse {
            get {
                return ResourceManager.GetString("RegistrationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exception while updating device with registration id: {0} and device token: {1}&quot;.
        /// </summary>
        internal static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating device for push notifications executing.
        /// </summary>
        internal static string UpdateExecute {
            get {
                return ResourceManager.GetString("UpdateExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Update registration for device id: {0} responded with registration id: {1}, tags: {2}&quot;.
        /// </summary>
        internal static string UpdateRegistrationResponse {
            get {
                return ResourceManager.GetString("UpdateRegistrationResponse", resourceCulture);
            }
        }
    }
}
