//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appva.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appva.Core.Resources.PermissionTypes", typeof(PermissionTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/calendar/event/create.
        /// </summary>
        public static string CreateCalendarEvent {
            get {
                return ResourceManager.GetString("CreateCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/create.
        /// </summary>
        public static string CreateDelegation {
            get {
                return ResourceManager.GetString("CreateDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/inventory/create.
        /// </summary>
        public static string CreateInventory {
            get {
                return ResourceManager.GetString("CreateInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/notification/create.
        /// </summary>
        public static string CreateNotification {
            get {
                return ResourceManager.GetString("CreateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/create.
        /// </summary>
        public static string CreatePatient {
            get {
                return ResourceManager.GetString("CreatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/create.
        /// </summary>
        public static string CreatePractitioner {
            get {
                return ResourceManager.GetString("CreatePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/role/create.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/create.
        /// </summary>
        public static string CreateSchedule {
            get {
                return ResourceManager.GetString("CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/calendar/event/delete.
        /// </summary>
        public static string DeleteCalendarEvent {
            get {
                return ResourceManager.GetString("DeleteCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/delete.
        /// </summary>
        public static string DeleteDelegation {
            get {
                return ResourceManager.GetString("DeleteDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/inventory/delete.
        /// </summary>
        public static string DeleteInventory {
            get {
                return ResourceManager.GetString("DeleteInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/notification/delete.
        /// </summary>
        public static string DeleteNotification {
            get {
                return ResourceManager.GetString("DeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/delete.
        /// </summary>
        public static string DeletePatient {
            get {
                return ResourceManager.GetString("DeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delete.
        /// </summary>
        public static string DeletePractitioner {
            get {
                return ResourceManager.GetString("DeletePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/role/delete.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/delete.
        /// </summary>
        public static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/sequence/print.
        /// </summary>
        public static string PrintSequence {
            get {
                return ResourceManager.GetString("PrintSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/alerts/read.
        /// </summary>
        public static string ReadAlert {
            get {
                return ResourceManager.GetString("ReadAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/area51/read.
        /// </summary>
        public static string ReadArea51 {
            get {
                return ResourceManager.GetString("ReadArea51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/calendar/event/read.
        /// </summary>
        public static string ReadCalendarEvent {
            get {
                return ResourceManager.GetString("ReadCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/dashboard/read.
        /// </summary>
        public static string ReadDashboard {
            get {
                return ResourceManager.GetString("ReadDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/read.
        /// </summary>
        public static string ReadDelegation {
            get {
                return ResourceManager.GetString("ReadDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/event/read.
        /// </summary>
        public static string ReadEventList {
            get {
                return ResourceManager.GetString("ReadEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/inventory/read.
        /// </summary>
        public static string ReadInventory {
            get {
                return ResourceManager.GetString("ReadInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/issued/read.
        /// </summary>
        public static string ReadIssuedDelegation {
            get {
                return ResourceManager.GetString("ReadIssuedDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/notification/read.
        /// </summary>
        public static string ReadNotification {
            get {
                return ResourceManager.GetString("ReadNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/read.
        /// </summary>
        public static string ReadPatient {
            get {
                return ResourceManager.GetString("ReadPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/read.
        /// </summary>
        public static string ReadPractitioner {
            get {
                return ResourceManager.GetString("ReadPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/report/read.
        /// </summary>
        public static string ReadPractitionerReport {
            get {
                return ResourceManager.GetString("ReadPractitionerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/revision/read.
        /// </summary>
        public static string ReadRevision {
            get {
                return ResourceManager.GetString("ReadRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/role/read.
        /// </summary>
        public static string ReadRole {
            get {
                return ResourceManager.GetString("ReadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/read.
        /// </summary>
        public static string ReadSchedule {
            get {
                return ResourceManager.GetString("ReadSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/report/read.
        /// </summary>
        public static string ReadScheduleReport {
            get {
                return ResourceManager.GetString("ReadScheduleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/alerts/update.
        /// </summary>
        public static string UpdateAlert {
            get {
                return ResourceManager.GetString("UpdateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/calendar/event/update.
        /// </summary>
        public static string UpdateCalendarEvent {
            get {
                return ResourceManager.GetString("UpdateCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/delegation/update.
        /// </summary>
        public static string UpdateDelegation {
            get {
                return ResourceManager.GetString("UpdateDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/inventory/update.
        /// </summary>
        public static string UpdateInventory {
            get {
                return ResourceManager.GetString("UpdateInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/notification/update.
        /// </summary>
        public static string UpdateNotification {
            get {
                return ResourceManager.GetString("UpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/update.
        /// </summary>
        public static string UpdatePatient {
            get {
                return ResourceManager.GetString("UpdatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/update.
        /// </summary>
        public static string UpdatePractitioner {
            get {
                return ResourceManager.GetString("UpdatePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/practitioner/role/update.
        /// </summary>
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://schema.appva.se/permission/patient/schedule/update.
        /// </summary>
        public static string UpdateSchedule {
            get {
                return ResourceManager.GetString("UpdateSchedule", resourceCulture);
            }
        }
    }
}
