//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appva.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoleTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appva.Core.Resources.RoleTypes", typeof(RoleTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ADMIN_AS.
        /// </summary>
        public static string AdministrativePersonnel {
            get {
                return ResourceManager.GetString("AdministrativePersonnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ADMIN_.
        /// </summary>
        public static string AdminPrefix {
            get {
                return ResourceManager.GetString("AdminPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AA.
        /// </summary>
        public static string Appva {
            get {
                return ResourceManager.GetString("Appva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_AN.
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _BA.
        /// </summary>
        public static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ADMIN_D.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _DA.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_D.
        /// </summary>
        public static string Dietician {
            get {
                return ResourceManager.GetString("Dietician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ESC.
        /// </summary>
        public static string Escalation {
            get {
                return ResourceManager.GetString("Escalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_N.
        /// </summary>
        public static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_N_AT.
        /// </summary>
        public static string OccupationalTherapist {
            get {
                return ResourceManager.GetString("OccupationalTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_N_SG.
        /// </summary>
        public static string Physiotherapist {
            get {
                return ResourceManager.GetString("Physiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SA.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_.
        /// </summary>
        public static string TitlePrefix {
            get {
                return ResourceManager.GetString("TitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TITLE_P.
        /// </summary>
        public static string UnqualifiedAssistant {
            get {
                return ResourceManager.GetString("UnqualifiedAssistant", resourceCulture);
            }
        }
    }
}
