//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appva.Azure.Debug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appva.Azure.Debug.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PushNotification&gt; Initialized.
        /// </summary>
        internal static string ConstructorInitialization {
            get {
                return ResourceManager.GetString("ConstructorInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SendPush&gt; Exception raised for &lt;tags&gt;: {0} with &lt;payload&gt;: {1}.
        /// </summary>
        internal static string PushException {
            get {
                return ResourceManager.GetString("PushException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SendPush&gt;Executing for &lt;tags&gt;: {0}.
        /// </summary>
        internal static string PushExecuting {
            get {
                return ResourceManager.GetString("PushExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SendPush&gt; Response: &lt;success&gt;: {0} &lt;failure&gt;: {1} &lt;state&gt;: {2}.
        /// </summary>
        internal static string PushResponse {
            get {
                return ResourceManager.GetString("PushResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RegisterDevice&gt;Exception raised for &lt;device token&gt;: {0}.
        /// </summary>
        internal static string RegistrationException {
            get {
                return ResourceManager.GetString("RegistrationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RegisterDevice&gt; Executing for &lt;device token&gt;: {0}.
        /// </summary>
        internal static string RegistrationExecuting {
            get {
                return ResourceManager.GetString("RegistrationExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RegisterDevice&gt; Response: {0}.
        /// </summary>
        internal static string RegistrationResponse {
            get {
                return ResourceManager.GetString("RegistrationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UpdateDevice&gt; Exception raised for &lt;registration id&gt;: {0} and &lt;device token&gt;: {1}.
        /// </summary>
        internal static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UpdateDevice&gt; Executing for &lt;registration id&gt;: {0} with &lt;device token&gt;: {1}.
        /// </summary>
        internal static string UpdateExecute {
            get {
                return ResourceManager.GetString("UpdateExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UpdateDevice&gt; Response: {0}.
        /// </summary>
        internal static string UpdateResponse {
            get {
                return ResourceManager.GetString("UpdateResponse", resourceCulture);
            }
        }
    }
}
