//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appva.Apis.TenantServer.Legacy.Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenantDto", Namespace="http://schemas.datacontract.org/2004/07/Appva.Mcss.Wcf.Data")]
    [System.SerializableAttribute()]
    internal partial class TenantDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Appva.Apis.TenantServer.Legacy.Wcf.ConnectionDto ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchedulerStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Appva.Apis.TenantServer.Legacy.Wcf.ConnectionDto Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Hostname {
            get {
                return this.HostnameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostnameField, value) != true)) {
                    this.HostnameField = value;
                    this.RaisePropertyChanged("Hostname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SchedulerStatus {
            get {
                return this.SchedulerStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulerStatusField, value) != true)) {
                    this.SchedulerStatusField = value;
                    this.RaisePropertyChanged("SchedulerStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<string> Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionDto", Namespace="http://schemas.datacontract.org/2004/07/Appva.Mcss.Wcf.Data")]
    [System.SerializableAttribute()]
    internal partial class ConnectionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailOverPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrustedConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Database {
            get {
                return this.DatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseField, value) != true)) {
                    this.DatabaseField = value;
                    this.RaisePropertyChanged("Database");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FailOverPartner {
            get {
                return this.FailOverPartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.FailOverPartnerField, value) != true)) {
                    this.FailOverPartnerField = value;
                    this.RaisePropertyChanged("FailOverPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Server {
            get {
                return this.ServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerField, value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TrustedConnection {
            get {
                return this.TrustedConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.TrustedConnectionField, value) != true)) {
                    this.TrustedConnectionField = value;
                    this.RaisePropertyChanged("TrustedConnection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDto", Namespace="http://schemas.datacontract.org/2004/07/Appva.Mcss.Wcf.Data")]
    [System.SerializableAttribute()]
    internal partial class LogDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Tenant {
            get {
                return this.TenantField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantField, value) != true)) {
                    this.TenantField = value;
                    this.RaisePropertyChanged("Tenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf.ITenantService")]
    internal interface ITenantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Find", ReplyAction="http://tempuri.org/ITenantService/FindResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.FindResponse Find(Appva.Apis.TenantServer.Legacy.Wcf.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Find", ReplyAction="http://tempuri.org/ITenantService/FindResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.FindResponse> FindAsync(Appva.Apis.TenantServer.Legacy.Wcf.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/FindByContext", ReplyAction="http://tempuri.org/ITenantService/FindByContextResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.FindByContextResponse FindByContext(Appva.Apis.TenantServer.Legacy.Wcf.FindByContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/FindByContext", ReplyAction="http://tempuri.org/ITenantService/FindByContextResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.FindByContextResponse> FindByContextAsync(Appva.Apis.TenantServer.Legacy.Wcf.FindByContextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Load", ReplyAction="http://tempuri.org/ITenantService/LoadResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.LoadResponse Load(Appva.Apis.TenantServer.Legacy.Wcf.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Load", ReplyAction="http://tempuri.org/ITenantService/LoadResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.LoadResponse> LoadAsync(Appva.Apis.TenantServer.Legacy.Wcf.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Persist", ReplyAction="http://tempuri.org/ITenantService/PersistResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.PersistResponse Persist(Appva.Apis.TenantServer.Legacy.Wcf.PersistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Persist", ReplyAction="http://tempuri.org/ITenantService/PersistResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.PersistResponse> PersistAsync(Appva.Apis.TenantServer.Legacy.Wcf.PersistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Merge", ReplyAction="http://tempuri.org/ITenantService/MergeResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.MergeResponse Merge(Appva.Apis.TenantServer.Legacy.Wcf.MergeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Merge", ReplyAction="http://tempuri.org/ITenantService/MergeResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.MergeResponse> MergeAsync(Appva.Apis.TenantServer.Legacy.Wcf.MergeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Remove", ReplyAction="http://tempuri.org/ITenantService/RemoveResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.RemoveResponse Remove(Appva.Apis.TenantServer.Legacy.Wcf.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Remove", ReplyAction="http://tempuri.org/ITenantService/RemoveResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.RemoveResponse> RemoveAsync(Appva.Apis.TenantServer.Legacy.Wcf.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Inactivate", ReplyAction="http://tempuri.org/ITenantService/InactivateResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.InactivateResponse Inactivate(Appva.Apis.TenantServer.Legacy.Wcf.InactivateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/Inactivate", ReplyAction="http://tempuri.org/ITenantService/InactivateResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.InactivateResponse> InactivateAsync(Appva.Apis.TenantServer.Legacy.Wcf.InactivateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITenantService/Log")]
        void Log(Appva.Apis.TenantServer.Legacy.Wcf.Log request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITenantService/Log")]
        System.Threading.Tasks.Task LogAsync(Appva.Apis.TenantServer.Legacy.Wcf.Log request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/LoadLogs", ReplyAction="http://tempuri.org/ITenantService/LoadLogsResponse")]
        Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsResponse LoadLogs(Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITenantService/LoadLogs", ReplyAction="http://tempuri.org/ITenantService/LoadLogsResponse")]
        System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsResponse> LoadLogsAsync(Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        public FindRequest() {
        }
        
        public FindRequest(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto FindResult;
        
        public FindResponse() {
        }
        
        public FindResponse(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByContext", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FindByContextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string context;
        
        public FindByContextRequest() {
        }
        
        public FindByContextRequest(string context) {
            this.context = context;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByContextResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FindByContextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto FindByContextResult;
        
        public FindByContextResponse() {
        }
        
        public FindByContextResponse(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto FindByContextResult) {
            this.FindByContextResult = FindByContextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Load", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LoadRequest {
        
        public LoadRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Appva.Apis.TenantServer.Legacy.Wcf.TenantDto> LoadResult;
        
        public LoadResponse() {
        }
        
        public LoadResponse(System.Collections.Generic.List<Appva.Apis.TenantServer.Legacy.Wcf.TenantDto> LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Persist", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class PersistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant;
        
        public PersistRequest() {
        }
        
        public PersistRequest(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant) {
            this.tenant = tenant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PersistResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class PersistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto PersistResult;
        
        public PersistResponse() {
        }
        
        public PersistResponse(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto PersistResult) {
            this.PersistResult = PersistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Merge", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class MergeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant;
        
        public MergeRequest() {
        }
        
        public MergeRequest(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant) {
            this.tenant = tenant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MergeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class MergeResponse {
        
        public MergeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant) {
            this.tenant = tenant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class RemoveResponse {
        
        public RemoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Inactivate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class InactivateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant;
        
        public InactivateRequest() {
        }
        
        public InactivateRequest(Appva.Apis.TenantServer.Legacy.Wcf.TenantDto tenant) {
            this.tenant = tenant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InactivateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class InactivateResponse {
        
        public InactivateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Log", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class Log {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Appva.Apis.TenantServer.Legacy.Wcf.LogDto logDto;
        
        public Log() {
        }
        
        public Log(Appva.Apis.TenantServer.Legacy.Wcf.LogDto logDto) {
            this.logDto = logDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadLogs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LoadLogsRequest {
        
        public LoadLogsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadLogsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class LoadLogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Appva.Apis.TenantServer.Legacy.Wcf.LogDto> LoadLogsResult;
        
        public LoadLogsResponse() {
        }
        
        public LoadLogsResponse(System.Collections.Generic.List<Appva.Apis.TenantServer.Legacy.Wcf.LogDto> LoadLogsResult) {
            this.LoadLogsResult = LoadLogsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ITenantServiceChannel : Appva.Apis.TenantServer.Legacy.Wcf.ITenantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class TenantServiceClient : System.ServiceModel.ClientBase<Appva.Apis.TenantServer.Legacy.Wcf.ITenantService>, Appva.Apis.TenantServer.Legacy.Wcf.ITenantService {
        
        public TenantServiceClient() {
        }
        
        public TenantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TenantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TenantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.FindResponse Find(Appva.Apis.TenantServer.Legacy.Wcf.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.FindResponse> FindAsync(Appva.Apis.TenantServer.Legacy.Wcf.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.FindByContextResponse FindByContext(Appva.Apis.TenantServer.Legacy.Wcf.FindByContextRequest request) {
            return base.Channel.FindByContext(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.FindByContextResponse> FindByContextAsync(Appva.Apis.TenantServer.Legacy.Wcf.FindByContextRequest request) {
            return base.Channel.FindByContextAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.LoadResponse Load(Appva.Apis.TenantServer.Legacy.Wcf.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.LoadResponse> LoadAsync(Appva.Apis.TenantServer.Legacy.Wcf.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.PersistResponse Persist(Appva.Apis.TenantServer.Legacy.Wcf.PersistRequest request) {
            return base.Channel.Persist(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.PersistResponse> PersistAsync(Appva.Apis.TenantServer.Legacy.Wcf.PersistRequest request) {
            return base.Channel.PersistAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.MergeResponse Merge(Appva.Apis.TenantServer.Legacy.Wcf.MergeRequest request) {
            return base.Channel.Merge(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.MergeResponse> MergeAsync(Appva.Apis.TenantServer.Legacy.Wcf.MergeRequest request) {
            return base.Channel.MergeAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.RemoveResponse Remove(Appva.Apis.TenantServer.Legacy.Wcf.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.RemoveResponse> RemoveAsync(Appva.Apis.TenantServer.Legacy.Wcf.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.InactivateResponse Inactivate(Appva.Apis.TenantServer.Legacy.Wcf.InactivateRequest request) {
            return base.Channel.Inactivate(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.InactivateResponse> InactivateAsync(Appva.Apis.TenantServer.Legacy.Wcf.InactivateRequest request) {
            return base.Channel.InactivateAsync(request);
        }
        
        public void Log(Appva.Apis.TenantServer.Legacy.Wcf.Log request) {
            base.Channel.Log(request);
        }
        
        public System.Threading.Tasks.Task LogAsync(Appva.Apis.TenantServer.Legacy.Wcf.Log request) {
            return base.Channel.LogAsync(request);
        }
        
        public Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsResponse LoadLogs(Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsRequest request) {
            return base.Channel.LoadLogs(request);
        }
        
        public System.Threading.Tasks.Task<Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsResponse> LoadLogsAsync(Appva.Apis.TenantServer.Legacy.Wcf.LoadLogsRequest request) {
            return base.Channel.LoadLogsAsync(request);
        }
    }
}
